// Copyright (c) 2015 VigLink
/*
 VigLink JavaScript Library -- http://www.viglink.com

 Permission is hereby granted to create derivative works, but only for use
 with the VigLink web service.

 Includes:

 Sizzle CSS Selector Engine v1.10.20-pre
 http://sizzlejs.com/

 Copyright 2013 jQuery Foundation, Inc. and other contributors
 Released under the MIT license
 http://jquery.org/license

 Date: 2014-05-22
*/
(function(m){var d,b={_breaker:{},_start:null,each:function(){var a;return function(c,e,f){var h,d;d=b.type(c);var k=new Date;if(1===arguments.length)a=arguments[0];else if(f=b.extend({timeout:!1},f),"object"===d&&c.hasOwnProperty)for(h in c){if(c.hasOwnProperty(h)&&(e(c[h],h)===b._breaker||f.timeout&&b.elapsed(k)>a))break}else if(c){h=0;for(d=c.length;h<d&&!(e(c[h],h)===b._breaker||f.timeout&&b.elapsed(k)>a);h++);}}}(),extend:function(a){var c,e,b,h,d=arguments.length;a=a||{};for(e=1;e<d;e++)if(h=
arguments[e],void 0!==h&&null!==h)for(b in h)c=h[b],a!==c&&void 0!==c&&(a[b]=c);return a},noop:function(){},type:function(){var a=function(c,a){try{return("function"===typeof window[a]||"object"===typeof window[a])&&c instanceof window[a]}catch(b){}return!1};return function(c){return null===c?"null":void 0===c?"undefined":a(c,"HTMLElement")||"object"===typeof c&&1===c.nodeType&&"string"===typeof c.nodeName?"element":c==c.window?"window":a(c,"HTMLDocument")||"object"===typeof c&&("defaultView"in c||
"parentWindow"in c)?"document":Object.prototype.toString.call(c).slice(8,-1).toLowerCase()}}()};b.extend(b,{addClass:function(a,c){b.hasClass(a,c)||(a.className=(a.className?a.className+" ":"")+c)},all:function(a,c){var e="array"===b.type(a)?[]:{};b.each(a,function(a,h){c(a,h)&&("array"===b.type(e)?e.push(a):e[h]=a)});return e},ancestors:function(a){for(var c=[a];(a=a.parentNode)&&1===a.nodeType;)c.push(a);return c},attrValues:function(a,c,e){return(c=a[c])&&c.split?c.split(e||" "):[]},batchable:function(a,
c){c=c||b.noop;var e=function(){return b.extend({batch:!0,timeout:100},c())},f=b.traits.cors&&b.traits.json,h=[],d=null,k=function(){null!==d&&(clearTimeout(d),d=null);1===h.length?a.apply(null,h[0].arguments):1<h.length&&a.apply(null,h);h=[]},g=function(){h.push({arguments:b.toArray(arguments),batch:!0});!f||!e().batch?k():null===d&&(d=setTimeout(b.entryPoint(b.bind(function(){k()},this)),e().timeout))};b.extend(g,{flush:k,now:a});return g},batchArgs:function(a,c){return b.map(a,function(a){return void 0===
c?a.arguments:a.arguments[c]})},batched:function(a){a=b.toArray(a);if("array"===b.type(a))return b.all(a,function(c){return"object"===b.type(c)&&c.batch&&"array"===b.type(c.arguments)}).length===a.length},bind:function(a,c){return function(){return a.apply(c,arguments)}},cache:function(){var a={},c="vglnk_"+(new Date).getTime(),e=0;return function(b,h,d){if(b){var k=b[c];if(k||void 0!==d)return k||(k=++e),a[k]||(b[c]=k,a[k]={}),void 0!==d&&(a[k][h]=d),"string"===typeof h?a[k][h]:a[k]}}}(),canonicalizeHostname:function(a){"string"===
typeof a&&(a=b.createA(a));try{return a.hostname?a.hostname.toString().toLowerCase().replace(/^www\./,"").replace(/:.*$/,""):""}catch(c){return""}},clone:function(a){return b.extend({},a)},contains:function(a,c){return Boolean(b.find(a,function(a){return a===c}))},context:function(a){"element"===b.type(a)&&(a=a.ownerDocument);"document"===b.type(a)&&(a=a.defaultView||a.parentWindow);if("window"===b.type(a))return a},contextIsAncestor:function(a,c){for(var e=a.self;e.parent&&e.parent!==e;)if(e=e.parent,
e===c)return!0;return!1},cors:function(a,c,e){var b,h=function(){e?e(b.responseText):eval(b.responseText)};b=new window.XMLHttpRequest;b.onreadystatechange=function(){4===b.readyState&&200===b.status&&h()};try{return b.open("POST",a),b.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),b.withCredentials=!0,b.send(c),!0}catch(d){return!1}},createA:function(a,c){return b.createEl("a",{href:a,target:c})},createEl:function(a,c,e,f){var h;a=(f||document).createElement(a);c=c||{};e=e||
{};for(h in c)void 0!==c[h]&&(a[h]=c[h]);b.css(a,e);return a},css:function(a,c){for(var b in c)try{a.style[b]=c[b]}catch(f){}return a},destructing:function(a){return function(c){var a=!1,b;return function(){a||(b=c.apply(null,arguments),a=!0);return b}}(a)},elapsed:function(a){return(a=a||this._start)?(new Date).getTime()-a.getTime():0},entryPoint:function(a){return b.exceptionLogger(function(){var c;b._start=new Date;b.observer.pause();c=a.apply(this,arguments);b.observer.resume();return c})},escapeRegExp:function(){var a;
return function(c){a=a||/([.*+?^${}()|[\]\\])/g;return c.replace(a,"\\$1")}}(),eventLink:function(a){var c,b=a.target||a.srcElement;do{try{c=b.nodeType}catch(f){break}if(1===c&&(a=b.tagName.toUpperCase(),"A"===a||"AREA"===a))return b;b=b.parentNode}while(b)},every:function(a,c){return Boolean(!b.some(a,function(a){return!c(a)}))},exceptionLogger:function(){var a=!1,c=b.noop;return function(b,f){if(void 0!==f)a=f,c=b;else return function(){if(a)try{return b.apply(this,arguments)}catch(f){c(f)}else return b.apply(this,
arguments)}}}(),find:function(a,c,e){var f;b.each(a,function(a,e){if(c(a,e))return f=a,b._breaker},e);return f},generateNodeFilter:function(){var a=function(a,b){var h,d;b=","+b.join(",")+",";h=0;for(d=a.length;h<d;h++)if(c(a[h],b))return!0;return!1},c=function(a,c){return-1!==c.indexOf(","+a+",")};return function(e){e=b.extend({custom:null,classes:[],rels:[],tags:[]},e);e.tags.length&&(e.tags=","+e.tags.join(",").toLowerCase()+",");return function(f,h){h=b.extend({ancestors:!0,self:!0},h);var d=
function(f,h){var d;if(d=!(e.tags.length&&c(f.nodeName.toLowerCase(),e.tags))){if(d=e.classes.length){d=e.classes;var r=b.attrValues(f,"className");d=a(d,r)}if(d=!d){if(d=e.rels.length)d=e.rels,r=b.attrValues(f,"rel"),d=c(f.nodeName.toLowerCase(),",a,")&&a(d,r);d=!d&&!("function"===b.type(e.custom)&&e.custom(f,h))}}return d};if(h.self&&!d(f,!0))return!1;if(h.ancestors)for(;f.parentNode;)if(f=f.parentNode,1===f.nodeType&&!d(f,!1))return!1;return!0}}}(),fromJSON:function(a){if(b.traits.json)try{return window.JSON.parse(a)}catch(c){}},
fromQuery:function(a){"?"===a.substr(0,1)&&(a=a.substr(1));a=a.split("&");var c={};b.each(a,function(a){a=a.split("=");c[decodeURIComponent(a[0])]=decodeURIComponent(a[1])});return c},geometry:function(){var a,c=arguments.length,e=Infinity,f=Infinity,h=-Infinity,d=-Infinity,k;for(a=0;a<c;a++)k=b.position(arguments[a]),e=Math.min(e,k.x),f=Math.min(f,k.y),h=Math.max(h,k.x+arguments[a].offsetWidth),d=Math.max(d,k.y+arguments[a].offsetHeight);return{x:e,y:f,w:h-e,h:d-f,x1:e,y1:f,x2:h,y2:d}},getActualHref:function(a){return b.cache(a,
"href")||a.href},hasAttrValue:function(a,c,e,f){return c?b.contains(b.attrValues(a,c,f),e):!1},hasClass:function(a,c){return b.hasAttrValue(a,"className",c)},hasRel:function(a,c){return b.hasAttrValue(a,"rel",c)},isArray:function(a){return"array"===b.type(a)},isDefaultPrevented:function(a){return a.isDefaultPrevented&&a.isDefaultPrevented()||!1===a.returnValue||!0===a.defaultPrevented},isInDom:function(a){return Boolean(a&&a.offsetParent)},jsonp:function(a){var c=document.getElementsByTagName("script")[0];
a=b.createEl("script",{type:"text/javascript",src:a});c.parentNode.insertBefore(a,c)},map:function(a,c,e){return b.reduce([],a,function(a,b,e){a.push(c(b,e));return a},e)},matches:function(a,c){if("element"!==b.type(a))return!1;try{return this.Sizzle.matchesSelector(a,c)}catch(e){return!0}},nodesOfType:function(a){var c=b.toArray(arguments).slice(1);return b.all(a,function(a){return b.contains(c,a.nodeType)})},on:function(){var a;return function(c,e,f){var h,d,k;if(1===arguments.length)a=c;else{if(2===
arguments.length){if(!a)return;f=e;e=c;c=a}else h=b.toArray(arguments).slice(3,arguments.length);try{d=c["on"+e]}catch(g){}"function"===typeof d&&(c["on"+e]=b.bind(function(a){a=a||window.event;var e=d.apply(c,arguments);this.exceptionLogger(function(){return a?(void 0!==e&&!1!==a.returnValue&&(a.returnValue=e),b.isDefaultPrevented(a)&&"function"===b.type(a.preventDefault)&&a.preventDefault(),a.returnValue):e})()},this));k=b.entryPoint(function(){if(a.enabled())return f.apply(null,b.toArray(arguments).concat(h||
[]))});c.addEventListener?c.addEventListener(e,k,!1):c.attachEvent&&c.attachEvent("on"+e,k)}}}(),position:function(a,c){var e,f=0,h=0,d=0,k=0;c=c||document;if(!b.isInDom(a))return!1;e=a;do f+=e.offsetLeft,h+=e.offsetTop,e=e.offsetParent;while(e);e=a;do d+=e.scrollLeft,k+=e.scrollTop,e=e.parentNode;while(e&&e!==c.body);return{x:f-d,y:h-k}},preventDefault:function(a){a.preventDefault&&a.preventDefault();return a.returnValue=!1},prune:function(a){b.each(a,function(c,b){(null===c||void 0===c)&&delete a[b]});
return a},ready:function(){var a=!1,c=[],e=!1,f,h,d,k,g;document.addEventListener?d=function(){document.removeEventListener("DOMContentLoaded",d,!1);g()}:document.attachEvent&&(k=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",k),g())});f=function(){if(!a){a=!0;if("interactive"===document.readyState||"complete"===document.readyState)return g();if(document.addEventListener)document.addEventListener("DOMContentLoaded",d,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",
k);var c=!1;try{c=null===window.frameElement}catch(e){}document.documentElement.doScroll&&c&&h()}b.on(window,"load",g)}};h=function(){if(!e){try{document.documentElement.doScroll("left")}catch(a){setTimeout(b.entryPoint(h),1);return}g()}};g=function(){if(!e){if(!document.body)return setTimeout(b.entryPoint(g),13);e=!0;c&&(b.each(c,function(a){a()}),c=null)}};return function(a){f();e?a():c.push(a)}}(),reduce:function(a,c,e,f){b.each(c,function(c,b){a=e(a,c,b)},f);return a},reformatKeys:function(a){var c,
e,f=function(a){return"_"+a.toLowerCase()};for(c in a)e=c.replace(/([A-Z])/g,f),"object"===b.type(a[c])&&(a[c]=b.reformatKeys(a[c])),e!==c&&(a[e]=a[c],delete a[c]);return a},removeClass:function(a,c){if(b.hasClass(a,c)){var e,f,h=b.attrValues(a,"className");e=0;for(f=h.length;e<f;e++)h[e]===c&&delete h[e];a.className=h.join(" ")}},request:function(a,c,e){var f,h,d,k=b.uniqid("vglnk_"),g=b.toArray(arguments).slice(3,arguments.length),q=function(a,c,e){var f=b.createA(a).protocol;c.length&&(a=b.updateUrl(a,
{search:"?"+c}));if(!0===e||!1===e)a=b.updateUrl(a,{protocol:f.replace(/s?:$/,function(){return e?"s:":":"})});return a};e=b.extend({fn:b.noop,jsonp:!0,"return":!1,ssl:null,timeout:null},e);"string"===typeof e.fn?(f=window[e.fn],k=e.fn):"function"===typeof e.fn&&(f=e.fn);"function"===b.type(f)&&(d=b.entryPoint(b.destructing(function(){f.apply(this,b.toArray(arguments).concat(g));window[k]&&(window[k]=void 0)})),null!==e.timeout&&setTimeout(d,e.timeout));!0===e.jsonp&&(window[k]=d,c=b.extend({format:"jsonp",
jsonp:k},c));h=b.toQuery(c);return e["return"]?q(a,h,e.ssl):b.traits.cors&&b.cors(q(a,"",e.ssl),h,e.jsonp?null:d)?!0:b.jsonp(q(a,h,e.ssl))},select:function(){try{return this.Sizzle.apply(this.Sizzle,arguments)}catch(a){return[]}},some:function(a,c){return Boolean(b.find(a,function(a){return c(a)}))},stopPropagation:function(a){a&&a.stopPropagation&&a.stopPropagation();a.cancelBubble=!0},toArray:function(a){if(a&&void 0!==a.length)try{return Array.prototype.slice.call(a,0)}catch(c){var b,f,h=[];b=
0;for(f=a.length;b<f;b++)h[b]=a[b];return h}},toJSON:function(a){if(b.traits.json)try{return window.JSON.stringify(a)}catch(c){}},toQuery:function(a){var c="";b.each(b.prune(a),function(a,b){c+="&"+encodeURIComponent(b)+"="+encodeURIComponent(a)});return c.substr(1)},updateUrl:function(a,c){return b.extend(b.createA(a),c).href},uniqid:function(){var a=0;return function(c){return(c||"")+(new Date).getTime()+a++}}(),unique:function(a){return b.reduce([],a,function(a,e){b.contains(a,e)||a.push(e);return a})},
unlink:function(a){var c,b=document.createDocumentFragment();if(a.parentNode){for(;null!==(c=a.firstChild);)b.appendChild(c);a.parentNode.insertBefore(b,a);a.parentNode.removeChild(a)}},withScope:function(){var a=function(a,e,f){if(f.self&&b.contains(e,a))return a;if(f.ancestors)return b.find(b.ancestors(a).slice(0),function(a){return b.contains(e,a)},{timeout:!0})};return function(c,e,f){var d=b.select(e);f=b.extend({ancestors:!0,consolidate:!1,descendants:!0,self:!0},f);c=b.all(b.map(c,function(c){var e,
g=[];(e=a(c,d,f))?g.push(e):1===c.nodeType&&f.descendants&&b.each(d,function(a){b.contains(b.ancestors(a),c)&&g.push(a)},{timeout:!0});return[c,g]},{timeout:!0}),function(a){return 0<a[1].length},{timeout:!0});return f.consolidate?b.reduce([],c,function(a,c){return a.concat(c[1])}):c}}()});var s=function(){var a=b.find(b.toArray(arguments),function(a){return"function"===b.type(a)});a&&(b.Sizzle=a())};s.amd=!0;(function(a){function c(a,c,b,e){var f,d,h,g,k;(c?c.ownerDocument||c:B)!==z&&H(c);c=c||z;
b=b||[];if(!a||"string"!==typeof a)return b;if(1!==(g=c.nodeType)&&9!==g)return[];if(D&&!e){if(f=sa.exec(a))if(h=f[1])if(9===g)if((d=c.getElementById(h))&&d.parentNode){if(d.id===h)return b.push(d),b}else return b;else{if(c.ownerDocument&&(d=c.ownerDocument.getElementById(h))&&R(c,d)&&d.id===h)return b.push(d),b}else{if(f[2])return I.apply(b,c.getElementsByTagName(a)),b;if((h=f[3])&&v.getElementsByClassName&&c.getElementsByClassName)return I.apply(b,c.getElementsByClassName(h)),b}if(v.qsa&&(!A||!A.test(a))){d=
f=x;h=c;k=9===g&&a;if(1===g&&"object"!==c.nodeName.toLowerCase()){g=S(a);(f=c.getAttribute("id"))?d=f.replace(ta,"\\$&"):c.setAttribute("id",d);d="[id='"+d+"'] ";for(h=g.length;h--;)g[h]=d+p(g[h]);h=ea.test(a)&&l(c.parentNode)||c;k=g.join(",")}if(k)try{return I.apply(b,h.querySelectorAll(k)),b}catch(q){}finally{f||c.removeAttribute("id")}}}return ka(a.replace(X,"$1"),c,b,e)}function b(){function a(b,e){c.push(b+" ")>t.cacheLength&&delete a[c.shift()];return a[b+" "]=e}var c=[];return a}function f(a){a[x]=
!0;return a}function d(a){var c=z.createElement("div");try{return!!a(c)}catch(b){return!1}finally{c.parentNode&&c.parentNode.removeChild(c)}}function g(a,c){for(var b=a.split("|"),e=a.length;e--;)t.attrHandle[b[e]]=c}function k(a,c){var b=c&&a,e=b&&1===a.nodeType&&1===c.nodeType&&(~c.sourceIndex||la)-(~a.sourceIndex||la);if(e)return e;if(b)for(;b=b.nextSibling;)if(b===c)return-1;return a?1:-1}function n(a){return function(c){return"input"===c.nodeName.toLowerCase()&&c.type===a}}function q(a){return function(c){var b=
c.nodeName.toLowerCase();return("input"===b||"button"===b)&&c.type===a}}function u(a){return f(function(c){c=+c;return f(function(b,e){for(var f,d=a([],b.length,c),h=d.length;h--;)if(b[f=d[h]])b[f]=!(e[f]=b[f])})})}function l(a){return a&&typeof a.getElementsByTagName!==N&&a}function m(){}function p(a){for(var c=0,b=a.length,e="";c<b;c++)e+=a[c].value;return e}function w(a,c,b){var e=c.dir,f=b&&"parentNode"===e,d=ua++;return c.first?function(c,b,d){for(;c=c[e];)if(1===c.nodeType||f)return a(c,b,d)}:
function(c,b,h){var W,ca,g=[C,d];if(h)for(;c=c[e];){if((1===c.nodeType||f)&&a(c,b,h))return!0}else for(;c=c[e];)if(1===c.nodeType||f){ca=c[x]||(c[x]={});if((W=ca[e])&&W[0]===C&&W[1]===d)return g[2]=W[2];ca[e]=g;if(g[2]=a(c,b,h))return!0}}}function fa(a){return 1<a.length?function(c,b,e){for(var f=a.length;f--;)if(!a[f](c,b,e))return!1;return!0}:a[0]}function Y(a,c,b,e,f){for(var d,h=[],g=0,k=a.length,q=null!=c;g<k;g++)if(d=a[g])if(!b||b(d,e,f))h.push(d),q&&c.push(g);return h}function ga(a,b,e,d,h,
g){d&&!d[x]&&(d=ga(d));h&&!h[x]&&(h=ga(h,g));return f(function(f,g,k,q){var n,r,u=[],y=[],l=g.length,m;if(!(m=f)){m=b||"*";for(var p=k.nodeType?[k]:k,Q=[],da=0,w=p.length;da<w;da++)c(m,p[da],Q);m=Q}m=a&&(f||!b)?Y(m,u,a,k,q):m;p=e?h||(f?a:l||d)?[]:g:m;e&&e(m,p,k,q);if(d){n=Y(p,y);d(n,[],k,q);for(k=n.length;k--;)if(r=n[k])p[y[k]]=!(m[y[k]]=r)}if(f){if(h||a){if(h){n=[];for(k=p.length;k--;)if(r=p[k])n.push(m[k]=r);h(null,p=[],n,q)}for(k=p.length;k--;)if((r=p[k])&&-1<(n=h?L.call(f,r):u[k]))f[n]=!(g[n]=
r)}}else p=Y(p===g?p.splice(l,p.length):p),h?h(null,g,p,q):I.apply(g,p)})}function T(a){var c,b,e,f=a.length,d=t.relative[a[0].type];b=d||t.relative[" "];for(var h=d?1:0,g=w(function(a){return a===c},b,!0),k=w(function(a){return-1<L.call(c,a)},b,!0),q=[function(a,b,e){return!d&&(e||b!==Z)||((c=b).nodeType?g(a,b,e):k(a,b,e))}];h<f;h++)if(b=t.relative[a[h].type])q=[w(fa(q),b)];else{b=t.filter[a[h].type].apply(null,a[h].matches);if(b[x]){for(e=++h;e<f&&!t.relative[a[e].type];e++);return ga(1<h&&fa(q),
1<h&&p(a.slice(0,h-1).concat({value:" "===a[h-2].type?"*":""})).replace(X,"$1"),b,h<e&&T(a.slice(h,e)),e<f&&T(a=a.slice(e)),e<f&&p(a))}q.push(b)}return fa(q)}function va(a,b){var e=0<b.length,d=0<a.length,h=function(f,h,g,k,q){var n,r,u,y=0,l="0",p=f&&[],m=[],Q=Z,ja=f||d&&t.find.TAG("*",q),w=C+=null==Q?1:Math.random()||0.1,ra=ja.length;for(q&&(Z=h!==z&&h);l!==ra&&null!=(n=ja[l]);l++){if(d&&n){for(r=0;u=a[r++];)if(u(n,h,g)){k.push(n);break}q&&(C=w)}e&&((n=!u&&n)&&y--,f&&p.push(n))}y+=l;if(e&&l!==y){for(r=
0;u=b[r++];)u(p,m,h,g);if(f){if(0<y)for(;l--;)!p[l]&&!m[l]&&(m[l]=wa.call(k));m=Y(m)}I.apply(k,m);q&&(!f&&0<m.length&&1<y+b.length)&&c.uniqueSort(k)}q&&(C=w,Z=Q);return p};return e?f(h):h}var O,v,t,$,ma,S,ha,ka,Z,J,P,H,z,E,D,A,M,aa,R,x="sizzle"+-new Date,B=a.document,C=0,ua=0,na=b(),oa=b(),pa=b(),ia=function(a,c){a===c&&(P=!0);return 0},N="undefined",la=-2147483648,xa={}.hasOwnProperty,K=[],wa=K.pop,ya=K.push,I=K.push,qa=K.slice,L=K.indexOf||function(a){for(var c=0,b=this.length;c<b;c++)if(this[c]===
a)return c;return-1},X=/^[\x20\t\r\n\f]+|((?:^|[^\\])(?:\\.)*)[\x20\t\r\n\f]+$/g,za=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,Aa=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,Ba=/=[\x20\t\r\n\f]*([^\]'"]*?)[\x20\t\r\n\f]*\]/g,Ca=RegExp(":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)"),
Da=/^(?:\\.|[\w-]|[^\x00-\xa0])+$/,ba={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:/^((?:\\.|[\w-]|[^\x00-\xa0])+|[*])/,ATTR:RegExp("^\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\]"),PSEUDO:RegExp("^:((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)"),
CHILD:RegExp("^:(only|first|last|nth|nth-last)-(child|of-type)(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)","i"),bool:RegExp("^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$","i"),needsContext:RegExp("^[\\x20\\t\\r\\n\\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\\([\\x20\\t\\r\\n\\f]*((?:-\\d)?\\d*)[\\x20\\t\\r\\n\\f]*\\)|)(?=[^-]|$)",
"i")},Ea=/^(?:input|select|textarea|button)$/i,Fa=/^h\d$/i,U=/^[^{]+\{\s*\[native \w/,sa=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,ea=/[+~]/,ta=/'|\\/g,F=/\\([\da-f]{1,6}[\x20\t\r\n\f]?|([\x20\t\r\n\f])|.)/ig,G=function(a,c,b){a="0x"+c-65536;return a!==a||b?c:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,a&1023|56320)};try{I.apply(K=qa.call(B.childNodes),B.childNodes),K[B.childNodes.length].nodeType}catch(Ga){I={apply:K.length?function(a,c){ya.apply(a,qa.call(c))}:function(a,c){for(var b=
a.length,e=0;a[b++]=c[e++];);a.length=b-1}}}v=c.support={};ma=c.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};H=c.setDocument=function(a){var c=a?a.ownerDocument||a:B;a=c.defaultView;if(c===z||9!==c.nodeType||!c.documentElement)return z;z=c;E=c.documentElement;D=!ma(c);a&&a!==a.top&&(a.addEventListener?a.addEventListener("unload",function(){H()},!1):a.attachEvent&&a.attachEvent("onunload",function(){H()}));v.attributes=d(function(a){a.className="i";return!a.getAttribute("className")});
v.getElementsByTagName=d(function(a){a.appendChild(c.createComment(""));return!a.getElementsByTagName("*").length});v.getElementsByClassName=U.test(c.getElementsByClassName)&&d(function(a){a.innerHTML="<div class='a'></div><div class='a i'></div>";a.firstChild.className="i";return 2===a.getElementsByClassName("i").length});v.getById=d(function(a){E.appendChild(a).id=x;return!c.getElementsByName||!c.getElementsByName(x).length});v.getById?(t.find.ID=function(a,c){if(typeof c.getElementById!==N&&D){var b=
c.getElementById(a);return b&&b.parentNode?[b]:[]}},t.filter.ID=function(a){var c=a.replace(F,G);return function(a){return a.getAttribute("id")===c}}):(delete t.find.ID,t.filter.ID=function(a){var c=a.replace(F,G);return function(a){return(a=typeof a.getAttributeNode!==N&&a.getAttributeNode("id"))&&a.value===c}});t.find.TAG=v.getElementsByTagName?function(a,c){if(typeof c.getElementsByTagName!==N)return c.getElementsByTagName(a)}:function(a,c){var b,e=[],f=0,d=c.getElementsByTagName(a);if("*"===a){for(;b=
d[f++];)1===b.nodeType&&e.push(b);return e}return d};t.find.CLASS=v.getElementsByClassName&&function(a,c){if(typeof c.getElementsByClassName!==N&&D)return c.getElementsByClassName(a)};M=[];A=[];if(v.qsa=U.test(c.querySelectorAll))d(function(a){a.innerHTML="<select msallowclip=''><option selected=''></option></select>";a.querySelectorAll("[msallowclip^='']").length&&A.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||A.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");
a.querySelectorAll(":checked").length||A.push(":checked")}),d(function(a){var b=c.createElement("input");b.setAttribute("type","hidden");a.appendChild(b).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&A.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");a.querySelectorAll(":enabled").length||A.push(":enabled",":disabled");a.querySelectorAll("*,:x");A.push(",.*:")});(v.matchesSelector=U.test(aa=E.matches||E.webkitMatchesSelector||E.mozMatchesSelector||E.oMatchesSelector||E.msMatchesSelector))&&
d(function(a){v.disconnectedMatch=aa.call(a,"div");aa.call(a,"[s!='']:x");M.push("!=",":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)")});A=A.length&&RegExp(A.join("|"));M=M.length&&RegExp(M.join("|"));
R=(a=U.test(E.compareDocumentPosition))||U.test(E.contains)?function(a,c){var b=9===a.nodeType?a.documentElement:a,e=c&&c.parentNode;return a===e||!(!e||!(1===e.nodeType&&(b.contains?b.contains(e):a.compareDocumentPosition&&a.compareDocumentPosition(e)&16)))}:function(a,c){if(c)for(;c=c.parentNode;)if(c===a)return!0;return!1};ia=a?function(a,b){if(a===b)return P=!0,0;var e=!a.compareDocumentPosition-!b.compareDocumentPosition;if(e)return e;e=(a.ownerDocument||a)===(b.ownerDocument||b)?a.compareDocumentPosition(b):
1;return e&1||!v.sortDetached&&b.compareDocumentPosition(a)===e?a===c||a.ownerDocument===B&&R(B,a)?-1:b===c||b.ownerDocument===B&&R(B,b)?1:J?L.call(J,a)-L.call(J,b):0:e&4?-1:1}:function(a,b){if(a===b)return P=!0,0;var e,f=0;e=a.parentNode;var d=b.parentNode,h=[a],V=[b];if(!e||!d)return a===c?-1:b===c?1:e?-1:d?1:J?L.call(J,a)-L.call(J,b):0;if(e===d)return k(a,b);for(e=a;e=e.parentNode;)h.unshift(e);for(e=b;e=e.parentNode;)V.unshift(e);for(;h[f]===V[f];)f++;return f?k(h[f],V[f]):h[f]===B?-1:V[f]===
B?1:0};return c};c.matches=function(a,b){return c(a,null,null,b)};c.matchesSelector=function(a,b){(a.ownerDocument||a)!==z&&H(a);b=b.replace(Ba,"='$1']");if(v.matchesSelector&&D&&(!M||!M.test(b))&&(!A||!A.test(b)))try{var e=aa.call(a,b);if(e||v.disconnectedMatch||a.document&&11!==a.document.nodeType)return e}catch(f){}return 0<c(b,z,null,[a]).length};c.contains=function(a,c){(a.ownerDocument||a)!==z&&H(a);return R(a,c)};c.attr=function(a,c){(a.ownerDocument||a)!==z&&H(a);var b=t.attrHandle[c.toLowerCase()],
b=b&&xa.call(t.attrHandle,c.toLowerCase())?b(a,c,!D):void 0;return void 0!==b?b:v.attributes||!D?a.getAttribute(c):(b=a.getAttributeNode(c))&&b.specified?b.value:null};c.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};c.uniqueSort=function(a){var c,b=[],e=0,f=0;P=!v.detectDuplicates;J=!v.sortStable&&a.slice(0);a.sort(ia);if(P){for(;c=a[f++];)c===a[f]&&(e=b.push(f));for(;e--;)a.splice(b[e],1)}J=null;return a};$=c.getText=function(a){var c,b="",e=0;if(c=a.nodeType)if(1===
c||9===c||11===c){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)b+=$(a)}else{if(3===c||4===c)return a.nodeValue}else for(;c=a[e++];)b+=$(c);return b};t=c.selectors={cacheLength:50,createPseudo:f,match:ba,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(F,G);a[3]=(a[3]||a[4]||a[5]||"").replace(F,G);"~="===
a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||c.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&c.error(a[0]);return a},PSEUDO:function(a){var c,b=!a[6]&&a[2];if(ba.CHILD.test(a[0]))return null;if(a[3])a[2]=a[4]||a[5]||"";else if(b&&Ca.test(b)&&(c=S(b,!0))&&(c=b.indexOf(")",b.length-c)-b.length))a[0]=a[0].slice(0,c),a[2]=b.slice(0,c);return a.slice(0,3)}},filter:{TAG:function(a){var c=
a.replace(F,G).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===c}},CLASS:function(a){var c=na[a+" "];return c||(c=RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"))&&na(a,function(a){return c.test("string"===typeof a.className&&a.className||typeof a.getAttribute!==N&&a.getAttribute("class")||"")})},ATTR:function(a,b,e){return function(f){f=c.attr(f,a);if(null==f)return"!="===b;if(!b)return!0;f+="";return"="===b?f===e:"!="===b?
f!==e:"^="===b?e&&0===f.indexOf(e):"*="===b?e&&-1<f.indexOf(e):"$="===b?e&&f.slice(-e.length)===e:"~="===b?-1<(" "+f+" ").indexOf(e):"|="===b?f===e||f.slice(0,e.length+1)===e+"-":!1}},CHILD:function(a,c,b,e,f){var d="nth"!==a.slice(0,3),h="last"!==a.slice(-4),g="of-type"===c;return 1===e&&0===f?function(a){return!!a.parentNode}:function(c,b,k){var q,n,r,u,y;b=d!==h?"nextSibling":"previousSibling";var l=c.parentNode,p=g&&c.nodeName.toLowerCase();k=!k&&!g;if(l){if(d){for(;b;){for(n=c;n=n[b];)if(g?n.nodeName.toLowerCase()===
p:1===n.nodeType)return!1;y=b="only"===a&&!y&&"nextSibling"}return!0}y=[h?l.firstChild:l.lastChild];if(h&&k){k=l[x]||(l[x]={});q=k[a]||[];u=q[0]===C&&q[1];r=q[0]===C&&q[2];for(n=u&&l.childNodes[u];n=++u&&n&&n[b]||(r=u=0)||y.pop();)if(1===n.nodeType&&++r&&n===c){k[a]=[C,u,r];break}}else if(k&&(q=(c[x]||(c[x]={}))[a])&&q[0]===C)r=q[1];else for(;n=++u&&n&&n[b]||(r=u=0)||y.pop();)if((g?n.nodeName.toLowerCase()===p:1===n.nodeType)&&++r)if(k&&((n[x]||(n[x]={}))[a]=[C,r]),n===c)break;r-=f;return r===e||
0===r%e&&0<=r/e}}},PSEUDO:function(a,b){var e,d=t.pseudos[a]||t.setFilters[a.toLowerCase()]||c.error("unsupported pseudo: "+a);return d[x]?d(b):1<d.length?(e=[a,a,"",b],t.setFilters.hasOwnProperty(a.toLowerCase())?f(function(a,c){for(var e,f=d(a,b),h=f.length;h--;)e=L.call(a,f[h]),a[e]=!(c[e]=f[h])}):function(a){return d(a,0,e)}):d}},pseudos:{not:f(function(a){var c=[],b=[],e=ha(a.replace(X,"$1"));return e[x]?f(function(a,c,b,f){f=e(a,null,f,[]);for(var d=a.length;d--;)if(b=f[d])a[d]=!(c[d]=b)}):
function(a,f,d){c[0]=a;e(c,null,d,b);return!b.pop()}}),has:f(function(a){return function(b){return 0<c(a,b).length}}),contains:f(function(a){a=a.replace(F,G);return function(c){return-1<(c.textContent||c.innerText||$(c)).indexOf(a)}}),lang:f(function(a){Da.test(a||"")||c.error("unsupported lang: "+a);a=a.replace(F,G).toLowerCase();return function(c){var b;do if(b=D?c.lang:c.getAttribute("xml:lang")||c.getAttribute("lang"))return b=b.toLowerCase(),b===a||0===b.indexOf(a+"-");while((c=c.parentNode)&&
1===c.nodeType);return!1}}),target:function(c){var b=a.location&&a.location.hash;return b&&b.slice(1)===c.id},root:function(a){return a===E},focus:function(a){return a===z.activeElement&&(!z.hasFocus||z.hasFocus())&&!(!a.type&&!a.href&&!~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var c=a.nodeName.toLowerCase();return"input"===c&&!!a.checked||"option"===c&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;
return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!t.pseudos.empty(a)},header:function(a){return Fa.test(a.nodeName)},input:function(a){return Ea.test(a.nodeName)},button:function(a){var c=a.nodeName.toLowerCase();return"input"===c&&"button"===a.type||"button"===c},text:function(a){var c;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(c=a.getAttribute("type"))||"text"===c.toLowerCase())},first:u(function(){return[0]}),
last:u(function(a,c){return[c-1]}),eq:u(function(a,c,b){return[0>b?b+c:b]}),even:u(function(a,c){for(var b=0;b<c;b+=2)a.push(b);return a}),odd:u(function(a,c){for(var b=1;b<c;b+=2)a.push(b);return a}),lt:u(function(a,c,b){for(c=0>b?b+c:b;0<=--c;)a.push(c);return a}),gt:u(function(a,c,b){for(b=0>b?b+c:b;++b<c;)a.push(b);return a})}};t.pseudos.nth=t.pseudos.eq;for(O in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})t.pseudos[O]=n(O);for(O in{submit:!0,reset:!0})t.pseudos[O]=q(O);m.prototype=t.filters=
t.pseudos;t.setFilters=new m;S=c.tokenize=function(a,b){var e,f,d,h,k,g,q;if(k=oa[a+" "])return b?0:k.slice(0);k=a;g=[];for(q=t.preFilter;k;){if(!e||(f=za.exec(k)))f&&(k=k.slice(f[0].length)||k),g.push(d=[]);e=!1;if(f=Aa.exec(k))e=f.shift(),d.push({value:e,type:f[0].replace(X," ")}),k=k.slice(e.length);for(h in t.filter)if((f=ba[h].exec(k))&&(!q[h]||(f=q[h](f))))e=f.shift(),d.push({value:e,type:h,matches:f}),k=k.slice(e.length);if(!e)break}return b?k.length:k?c.error(a):oa(a,g).slice(0)};ha=c.compile=
function(a,c){var b,e=[],f=[],d=pa[a+" "];if(!d){c||(c=S(a));for(b=c.length;b--;)d=T(c[b]),d[x]?e.push(d):f.push(d);d=pa(a,va(f,e));d.selector=a}return d};ka=c.select=function(a,c,b,e){var f,d,h,k,g="function"===typeof a&&a,q=!e&&S(a=g.selector||a);b=b||[];if(1===q.length){d=q[0]=q[0].slice(0);if(2<d.length&&"ID"===(h=d[0]).type&&v.getById&&9===c.nodeType&&D&&t.relative[d[1].type]){if(c=(t.find.ID(h.matches[0].replace(F,G),c)||[])[0])g&&(c=c.parentNode);else return b;a=a.slice(d.shift().value.length)}for(f=
ba.needsContext.test(a)?0:d.length;f--;){h=d[f];if(t.relative[k=h.type])break;if(k=t.find[k])if(e=k(h.matches[0].replace(F,G),ea.test(d[0].type)&&l(c.parentNode)||c)){d.splice(f,1);a=e.length&&p(d);if(!a)return I.apply(b,e),b;break}}}(g||ha(a,q))(e,c,!D,b,ea.test(a)&&l(c.parentNode)||c);return b};v.sortStable=x.split("").sort(ia).join("")===x;v.detectDuplicates=!!P;H();v.sortDetached=d(function(a){return a.compareDocumentPosition(z.createElement("div"))&1});d(function(a){a.innerHTML="<a href='#'></a>";
return"#"===a.firstChild.getAttribute("href")})||g("type|href|height|width",function(a,c,b){if(!b)return a.getAttribute(c,"type"===c.toLowerCase()?1:2)});(!v.attributes||!d(function(a){a.innerHTML="<input/>";a.firstChild.setAttribute("value","");return""===a.firstChild.getAttribute("value")}))&&g("value",function(a,c,b){if(!b&&"input"===a.nodeName.toLowerCase())return a.defaultValue});d(function(a){return null==a.getAttribute("disabled")})||g("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",
function(a,c,b){var e;if(!b)return!0===a[c]?c.toLowerCase():(e=a.getAttributeNode(c))&&e.specified?e.value:null});"function"===typeof s&&s.amd?s(function(){return c}):"undefined"!==typeof module&&module.exports?module.exports=c:a.Sizzle=c})(window);b.browser=function(){var a,c={},e=navigator.userAgent.toLowerCase().replace(/\s*[()]\s*/g,"; ").replace(/(\/[\w.]+)\s+/g,"$1; ").replace(/\;\s*$/,"").split(/;\s*/);b.each(e,function(b){a=(/[\/ :]([^\/ :]+)$/.exec(b)||[])[1];c[a?b.substr(0,b.length-a.length-
1).replace(/\d*$/,""):b]=a||!0});return{aol:c.aol,blackberry:c.blackberry,ie:c.msie||c.trident,ios:c.mobile&&c.safari,opera:c.opera,playstation:c.playstation,version:parseFloat(c.version||c.crios||c.msie)||!1}}();b.harmony={PASSIVE:1,UNSAFE_QUIRKSMODE_EVENTS:0.5,COMMERCIAL_LINK_EVENTS:0.1,LINK_EVENTS:-1,AGGRESSIVE:-1};b.harmony.DEFAULT=0;b.pii=function(){var a={email:/[A-Z0-9._%+-]+(?:%(?:25)*40|@)[A-Z0-9.-]+\.[A-Z]{2,4}/,numeric:/\d([^0-9A-Z]{0,4}\d){6,18}/},c={contains:function(a,c){return this.regexp(c).test(a)},
redact:function(a,c){return a.replace(this.regexp(c),"___")},regexp:function(c){c=b.extend({},c);var f=b.map(b.all(a,function(a,b){return!1!==c[b]}),function(a){return a.source});return RegExp("(\\b"+f.join("\\b|\\b")+"\\b)","gi")},transmits:function(a,c){return this.contains(a+" "+document.referrer,c||{numeric:!1})}};return{contains:b.bind(c.contains,c),redact:b.bind(c.redact,c),transmits:b.bind(c.transmits,c)}}();b.platforms=function(){var a={NONE:{id:"full",scope:"body",spec:{selector:"body"}},
bbp:{spec:{parser:/^post-(\d+)$/,selector:"div[id^='post-']"},scope:"li .post"},hdlr:{spec:{parser:/^post_(\d+)$/,selector:"div[id^='post_']"},scope:".post-content-area"},ipb:{spec:{parser:/^post_id_(\d+)$/,selector:"div[id^='post_id_']"},scope:".post_body .post"},phpb:{spec:{parser:/^p(\d+)$/,selector:"div.post[id^='p']"},scope:".postbody .content,.postbody .signature"},ubb:{spec:{parser:/^number(\d+)$/,parse_el:"span[id^=number]",selector:"a[name^='Post'] ~ table"},scope:".post_inner *[id^='body'],.post_inner .signature"},
vb3:{spec:{parser:/^post_message_(\d+)$/,selector:"div[id^='post_message_'], table[id^='post_message_'],section[id^='post_message_']"},scope:"div[id^='post_message_'],div[id^='post_message_'] ~ div:not([class])"},vb4:{spec:{parser:/^post_(\d+)$/,selector:"li[id^='post_']"},scope:".post-content,.postbody .content,.postbody .signature,ul.conversation-list .list-item-body"},wppr:{spec:{attributes:["id","className"],parser:/(?:^|\s)post-(\d+)(?:\s|$)/,selector:"article[class*='post-'], div[id^='post-']"}}},
c={getPostId:function(a){var c,d;if(this===b.platforms.NONE)return" ";d=this.spec.parse_el?b.select(this.spec.parse_el,a)[0]:a;b.find(this.spec.attributes||["id"],b.bind(function(a){c=d[a]?d[a].match(this.spec.parser):null;return Boolean(c)},this));if(c)return c[1]},getPostIds:function(a){var c=[];b.each(this.getPosts(a),b.bind(function(a){(a=this.getPostId(a))&&!b.contains(c,a)&&c.push(a)},this));return c.length?c:null},getPosts:function(a){var c=[];!a&&(document&&document.body)&&(a=[document.body]);
a&&this.spec&&(c=b.unique(b.reduce([],b.withScope(a,this.spec.selector),function(a,c){return a.concat(c[1])})));return c}};b.each(a,function(e,f){e.id=e.id||f;b.each(c,function(a,c){e[c]=b.bind(a,e)});a[f]=e});a.DEFAULT_POST_ID=" ";a.findById=function(a){return b.find(b.platforms,function(c){return c.id===a})};return a}();b.observer=function(){var a=[],c=0,e=function(a){c||a.observer.observe(a.context.document,{attributes:!1,characterData:!0,childList:!0,subtree:!0})};return{start:function(c,d){if(c.document&&
b.traits.mutation){var g={context:c,observer:new MutationObserver(b.entryPoint(function(a){var c=[];b.each(a,function(a){var e=[];"characterData"===a.type?a.target&&(e=[a.target]):a.addedNodes&&a.addedNodes.length&&(e=b.toArray(a.addedNodes));e.length&&(c=c.concat(e))});0<c.length&&d(c)}))};a.push(g);e(g)}},pause:function(){c++;b.each(a,function(a){a.observer.disconnect()})},resume:function(){c--;b.each(a,e)}}}();b.traits={basicCompatibility:!(b.browser.blackberry||b.browser.playstation),cors:window.XMLHttpRequest&&
void 0!==(new window.XMLHttpRequest).withCredentials,crossWindowCommunication:!b.browser.ios,json:Boolean(window.JSON)&&Boolean(window.JSON.stringify)&&Boolean(window.JSON.parse),jsRedirectSetsReferrer:b.browser.aol||!(b.browser.ie||b.browser.opera),mutation:window.MutationObserver&&!b.browser.ie,quirksMode:!Boolean(window.addEventListener),windowLevelHandlers:Boolean(window.addEventListener)};var g,l,n,p;d={EVENT_LEVEL_LINK:1,EVENT_LEVEL_TOP:2,PLUGIN_MANUAL:1,TYPE_ACCEPTABLE:"l",allowed:b.generateNodeFilter({classes:["norewrite"],
rels:["norewrite"],tags:"applet embed object head img input link meta param select button iframe option script style svg textarea title".split(" ")}),api:function(){var a=function(){var a=function(a,c){a=b.fromJSON(a)||{};b.each(a,function(a,e){var d=c[e],f;if(d&&d.callback&&a){if("string"===b.type(a)&&(f=a.match(/^[^(]+\((.*)\);?\s*$/)))a=b.fromJSON(f[1]);d.callback.apply(window,[a].concat(d.data||[]))}})};return function(e){var k={},g={};b.each(e,function(a){a=c.apply(this,a);var e=a.method;k[e]=
b.prune(a.params);g[e]={callback:a.opts.fn||b.noop,data:a.data}});f({data:g,method:"batch",params:b.extend(d.commonParams(),{batch:window.JSON.stringify(k)}),opts:{jsonp:!1,fn:function(c,b){a(c,b)}}})}}(),c=function(a,c,f){var n=b.toArray(arguments).slice(3,arguments.length),q=a,l=e(f),p;p=b.extend(d.commonParams(a),c);p.subId&&p.key!==g.key&&(p.subId=null);return{data:n,method:q,opts:l,params:p}},e=function(a){a=a||{};"function"===b.type(a.fn)&&(a.fn=function(c){return function(e){var d;"object"===
b.type(e)&&("array"===b.type(e.crawl)&&"object"===b.type(p.crawler)&&"function"===b.type(p.crawler.crawl))&&(d=b.map(e.crawl,function(a){return a+""}),delete e.crawl,p.crawler.crawl(d));return c.apply(a,arguments)}}(a.fn));return a},f=function(a){return b.request.apply(b,[g.api_url+"/"+a.method,a.params,a.opts].concat(a.data))};return b.batchable(function(){return b.batched(arguments)?a.call(this,b.batchArgs(arguments)):f(c.apply(this,arguments))},function(){return{batch:g.batch_calls,timeout:g.batch_call_timeout}})}(),
addEventListener:function(a,c){this.fire(a,c)},click:function(){var a=function(a,c){if("_self"===c)return a;if(b.traits.crossWindowCommunication&&b.traits.jsRedirectSetsReferrer){var d=a.open("",c);d.focus();return d}},c=function(a){var c=a.previousSibling,h=a.nextSibling,g=["",a.textContent,""],k=function(a,c){for(var b=a,e=b.data;(b=b[c+"Sibling"])&&3===b.nodeType;)e+=b.data;return e},n=function(a,c,b){a=a.replace(/\s+/g," ");c=c.replace(/\s+/g," ");b=b.replace(/\s+/g," ");a=a.replace(/^\s+/,"");
" "===c.substr(0,1)&&(c=c.substr(1),a+=" "!==a.substr(a.length-1,1)?" ":"");" "===c.substr(c.length-1,1)&&(c=c.substr(0,c.length-1),b=(" "!==b.substr(0,1)?" ":"")+b);b=b.replace(/\s+$/,"");return[a,c,b]};void 0!==g[1]&&(g[0]=c&&3===c.nodeType?k(c,"previous"):"",g[2]=h&&3===h.nodeType?k(h,"next"):"",g=n.apply(this,g),""!==g[0]&&""!==g[2]&&(g[0]=g[0].split(" ").reverse().slice(0,10+(" "===g[0].substr(g[0].length-1,1)?1:0)).reverse().join(" "),g[2]=g[2].split(" ").slice(0,10).join(" "),a={type:"context",
itype:(b.cache(a,"params")||{}).type,before:g[0],after:g[2],txt:g[1],loc:location.href,out:b.getActualHref(a),v:2},d.log("info",b.toQuery(a))))};return function(e,d){var h,n,k,l,q=b.context(e)||window;d=e.target||d;d=!d||d===q.name||"_top"===d&&q.top===q||"_parent"===d&&q.parent===q?"_self":d;k=a(q,d);if("_self"!==d&&(!b.traits.crossWindowCommunication||!b.traits.jsRedirectSetsReferrer))l="go";else try{if(void 0===k.document)throw!0;l="jsonp"}catch(p){l="go"}h=b.destructing(b.bind(function(){g.time_click&&
arguments.length&&this.logTime("clk");var a=b.toArray(arguments);a.unshift(e,k,d);this.onApiClick.apply(this,a)},this));b.cache(this,"link","string"===typeof e?e:b.getActualHref(e));if("string"===typeof e&&(e=b.createA(e,d),!this.processLink(e))||!g.enabled)return h();n=this.clickParams(e,l);this.logTime();g.log_context&&c(e);if("go"===l)this.redirect(this.api.now("click",n,{"return":!0}),q,k,d);else if(k===q)this.api.now("click",n,{fn:h,timeout:g.click_timeout});else{if(b.contextIsAncestor(q,k))return this.redirect(b.getActualHref(e),
q,k,d);h=b.entryPoint(h);setTimeout(function(){h()},g.click_timeout);k.document.open();k.callback=h;k.document.write("<html><head><title>"+b.getActualHref(e)+'</title><script type="text/javascript" src="'+this.api.now("click",n,{fn:"callback","return":!0})+'">\x3c/script></head></html>');k.document.close()}}}(),clickParams:function(a,c){var e=b.extend(b.cache(a,"params"),{format:c,out:b.getActualHref(a),ref:window.document.referrer||null,reaf:g.reaffiliate||null,title:window.document.title,txt:a.innerHTML,
loAsUuid:b.cache(a,"uuid")||null,rewrit:b.cache(a,"rewrit")});128<e.txt.length&&(e.txt=e.txt.replace(/<[^>]+>/g,""),e.txt=128<e.txt.length?e.txt.substr(0,125)+"...":e.txt);return e},commonParams:function(a){var c={drKey:g.key?null:g.dr_key,key:g.key,libId:g.library_id,subId:g.sub_id};("click"===a||"ping"===a)&&b.extend(c,{cuid:g.cuid,loc:location.href,v:1},c);return c},detectFiltering:function(){var a;try{a={},a=new function(){this.detect=function(a,c){function b(a,c){0==n||1E3<c?a(0==n&&g):setTimeout(function(){b(a,
2*c)},2*c)}function d(){--n||(g=!q&&l)}var g=!1,n=2,q=!1,l=!1;if("function"==typeof c){a+="?ch=*&rn=*";var p=11*Math.random(),m=new Image;m.onload=d;m.onerror=function(){q=!0;d()};m.src=a.replace(/\*/,1).replace(/\*/,p);m=new Image;m.onload=d;m.onerror=function(){l=!0;d()};m.src=a.replace(/\*/,2).replace(/\*/,p);b(c,250)}}}}catch(c){a={detect:function(a,c){c(!0)}}}return function(c){var d=b.updateUrl(g.asset_url,{pathname:"/images/pixel.gif"});a.detect(d,c)}}(),enabled:function(){if(g.enabled&&n!==
window&&window.vglnk&&(window.vglnk.key||"function"===typeof window.vglnk))g.enabled=!1;return g.enabled},expose:function(){return function(a,c){if((c=c||this[a])&&!p[a]){var e=p,f;f=c;f="function"===b.type(f)?b.entryPoint(b.bind(f,d)):f;e[a]=f}}}(),fire:function(){var a={};return function(c,e){c=c.toLowerCase();var d=a[c]||{fired:!1,listeners:[]};"function"===typeof e?d.fired?setTimeout(function(){e({type:c})},0):d.listeners.push(e):(d.fired=!0,b.each(d.listeners,function(a){"function"===typeof a&&
a({type:c})}),d.listeners=[]);a[c]=d}}(),handleRightClick:function(a,c){if(g.rewrite_modified&&a&&c)switch(c){case "setup":b.cache(a,"href")||b.cache(a,"href",a.href);a.href=this.api.now("click",this.clickParams(a,"go"),{"return":!0});setTimeout(b.entryPoint(b.bind(function(){this.handleRightClick(a,"teardown")},this)),0);break;case "teardown":b.cache(a,"href")&&(a.href=b.cache(a,"href"))}},harmony:function(a){return g.harmony_level<=a},init:function(){var a=function(){var a=!0===window.document.__v5k;
window.document.__v5k=!0;return!a};return function(){var c=this;l={};if(a()){try{c.initLibEvents(),c.initNamespace(),c.initOptions()}catch(e){}b.exceptionLogger(b.bind(c.logException,c),!g.dev);b.each(g.script_timeout);return b.entryPoint(function(){c.initProcessors();c.initDRApi();c.initApi();c.enabled()&&(c.initLegacyCallbacks(),c.ping())})()}}}(),initApi:function(){var a,c={};if(window.vglnk)for(a in window.vglnk)"_plugin"===a.substr(-7)&&(c[a]=window.vglnk[a]);p=n[m]=b.noop;this.expose("click");
this.expose("link",b.bind(function(a){"element"===b.type(a)&&a.href&&(this.initContext(b.context(a)),this.processLink(a))},this));this.expose("open",b.bind(this.click,this));this.expose("$",b.clone(b));this.expose("api");this.expose("api_now",b.bind(this.api.now,this.api));this.expose("harmony");this.expose("opt");this.expose("platform");this.expose("registerProcessor",function(){if(0<arguments.length)return d.registerProcessor.apply(d,arguments)});b.extend(p,p===window.vglnk?c:{})},initContext:function(){var a=
[];return function(c){if(void 0===c)return a;c&&!b.contains(a,c)&&(a.push(c),this.initLinks(c),this.initEvents(c))}}(),initDRApi:function(){var a=!1;window.DrivingRevenue=b.entryPoint(b.destructing(b.bind(function(){a=!0;g.dr_key=window.DR_id;this.enabled()&&this.ping()},this)));b.on("DOMReady",function(){if(!a)try{delete window.DrivingRevenue}catch(c){window.DrivingRevenue=void 0}})},initEvents:function(a){var c=b.traits.windowLevelHandlers?a:a.document,e=function(c){c=c||a.event;if((c=b.eventLink(c))&&
!b.cache(c,"evented"))n(d.EVENT_LEVEL_LINK,c),b.cache(c,"evented",!0)},f=function(a){b.observer.start(a,b.batchable(function(a){b.batched(arguments)&&(a=b.reduce([],b.batchArgs(arguments,0),function(a,c){return a.concat(c)}));a=b.all(b.unique(a),function(a){return Boolean(a.parentNode)&&d.allowed(a)});0<a.length&&(b.each(b.withScope(a,"a[href]",{ancestors:!1}),function(a){d.processLinks(a[1])}),b.each(l,function(c,b){c.opts.mode!==d.PLUGIN_MANUAL&&d.runPlugin(b,a)}))},function(){return{batch:g.batch_mutation,
timeout:g.batch_mutation_timeout}}))},h=function(a,c){return function(){var e=[a].concat(b.toArray(arguments));c.apply(d,e)}},n=function(a,c){b.on(c,"click",h(a,d.onClick));b.on(c,"contextmenu",h(a,d.onContextmenu))};if(g.dynamic)b.on("DOMReady",function(){f(a)});b.on(c,"copy",b.bind(d.onCopy,d));b.on(c,"mousedown",e);b.on("DOMReady",function(){b.each(a.document.links,function(a){b.on(a,"mousedown",e)})});(!b.traits.quirksMode||d.harmony(b.harmony.UNSAFE_QUIRKSMODE_EVENTS))&&n(d.EVENT_LEVEL_TOP,c)},
initLegacyOptions:function(){var a,c={DR_id:"dr_key",vglnk_api_key:"key",vglnk_cuid:"cuid",vglnk_domain:"api_url",vglnk_reaf:"reaffiliate",vglnk_subid:"sub_id"};for(a in c)void 0!==window[a]&&(p[c[a]]=window[a],"vglnk_domain"===a&&(p[c[a]]+="/api"))},initLegacyCallbacks:function(){var a,c={vl_cB:b.bind(this.onApiClick,this),vl_disable:function(){g.enabled=!1}};for(a in c)window[a]=c[a]},initLibEvents:function(){b.on(d);b.ready(b.bind(function(){this.fire("DOMReady")},this))},initLinks:function(a){var c=
b.bind(function(a){this.processLinks(b.toArray(a.document.links))},this);void 0===a?b.each(this.initContext(),c):c(a)},initNamespace:function(){window.vglnk&&window.vglnk.key&&(m="vglnk");var a=window,c=m.split("."),b;for(m=c.pop();0<c.length;)b=c.shift(),a[b]=a[b]||{},a=a[b];n=a;p=n[m]=n[m]||{}},initOptions:function(){var a;this.initLegacyOptions();g=b.extend(this.publicOptions({api_url:"//api.viglink.com/api",asset_url:"//cdn.viglink.com/api",cuid:null,dev:!1,dr_key:null,enabled:b.traits.basicCompatibility,
key:null,link_urls:!0,partner:null,platform:b.platforms.NONE.id,sub_id:null,reaffiliate:!1,commercial:null,harmony_level:b.harmony.DEFAULT,link_target:null,rewrite_any:!0,rewrite_modified:!1,rewrite_original:!0}),g,p,{batch_calls:!0,batch_call_timeout:100,batch_mutation:!0,batch_mutation_timeout:250,click_timeout:1E3,dynamic:!0,hop_timeout:2E3,debug:!1,library_id:null,log_context:!0,nofollow:{},norewrite:{},script_timeout:2E3,time_click:!1,time_ping:!1,testing_js:[],plugins:{crawler:{},harmony:{},
link_affiliation:{},modified_clicks:{}}});for(a in g)"_plugin"===a.substr(-7)&&delete g[a]},initPlugins:function(){var a,c=1,e={link_affiliation:"convert",link_optimization:"optimize",page_harmony:"harmony",partner_integration:"partners",product_linker:"insert",product_widget:"spotlight"},f=["spotlight"],h=["harmony"],n=function(b){return function(b){return function(){delete l[b].opts.mode;c=1;clearTimeout(a);m()}}(b)},k=function(a){var c;b.find(e,function(a,b){return"insert"===a&&(c=b)});a[c]||(a[c]=
{enabled:!0,key:g.key,link_phrases:!1});a[c].link_urls=g.link_urls;return a},m=function(){var e={_ran:!1,init:b.noop,initDocuments:b.noop,initNodes:b.noop,"public":{}},f=function(a,c){a.setup=a.setup||(window.vglnk?window.vglnk[c+"_plugin"]:null);"function"===b.type(a.setup)&&(Boolean(a.initDocuments)||(a=b.extend(a,e,a.setup(a.opts,b.clone(b),p,k(g.key))),a["public"]&&d.expose(c,a["public"],!1)),a.opts.mode!==d.PLUGIN_MANUAL&&d.runPlugin(c))},k=function(a){return function(){if(a){var c=b.toArray(arguments);
c.unshift("custom",a);d.log.apply(this,c)}}},n=function(a){return!Boolean(a._ran)};a=null;b.each(h,function(a){var c=l[a];c&&!Boolean(c._ran)&&f(c,a)});b.each(b.all(l,n),f);b.find(l,n)&&(a=setTimeout(b.entryPoint(m),Math.min(Math.max(Math.pow(2,++c),100),5E3)))},q=function(){setTimeout(function(){d.api.flush()},100);m();b.on("DOMReady",function(){setTimeout(d.api.flush,0)})};return function(a){a=k(a);b.each(a,b.bind(function(a,c){c=e[c]||c;"object"===typeof a&&!1!==a.enabled&&(l[c]={opts:a},b.contains(f,
c)&&b.jsonp(this.opt("asset_url")+"/plugins/"+c+".js"),a.mode===this.PLUGIN_MANUAL&&this.expose("init_"+c,n(c)))},this));q()}}(),initProcessors:function(){this.registerProcessor(function(a){var c;c=b.createA(g.api_url);if("/api/click"===a.pathname&&(a.hostname===c.hostname||a.hostname.match(/(^|\.)(api|cdn|apicdn)\.viglink\.com$/)))c=b.fromQuery(a.search),void 0!==c.out&&(a.href=c.out,delete c.out,b.cache(a,"params",c))});this.registerProcessor(function(a){g.nofollow[a.href]&&!b.hasRel(a,"nofollow")&&
(a.rel=(a.rel?a.rel+" ":"")+"nofollow")});this.registerProcessor(function(a){window.IPBoard&&(window.IPBoard.prototype&&window.IPBoard.prototype.delegate&&b.hasRel(a,"external"))&&(a.rel=a.rel.replace(/(^| )external( |$)/,""),a.target="_blank")})},isCommercial:function(a){a=b.canonicalizeHostname(a);return"object"===b.type(g.commercial)&&g.commercial[a]},isRewritable:function(){var a=b.canonicalizeHostname(document.location),c=b.generateNodeFilter({rels:["noskim"],custom:function(c){var f=b.canonicalizeHostname(c),
h="",n=!1;try{h=c.protocol,f.charAt(0)}catch(k){return!0}n=Boolean(""===f||!h.match(/^https?:$/i)||g.norewrite[f]);if(h=!n)var h=b.cache(c,"type"),l=b.cache(c,"params")||{},h=!Boolean(h||l.type);h&&(n=Boolean(a===f||!g.rewrite_original||!g.rewrite_any&&!d.isCommercial(c)));return n}});return function(a){return this.allowed(a)&&c(a,{ancestors:!1})}}(),log:function(a,c,e,d){var h,n=b.toQuery({libId:g.library_id,nocache:b.uniqid()});h="pixel.gif";if("custom"===a)n+="&"+b.toQuery({key:c,type:e}),b.each("array"===
b.type(d)?d:[d],function(a){b.each(["e","i","o"],function(c){delete a[c]});n+="&"+b.toQuery(a)});else{n+="&"+b.toQuery({key:g.key,drKey:g.key?null:g.dr_key,subId:g.sub_id});if("time"===a)h="time.gif",a={time:e,type:c};else if("exception"===a)a={e:c,o:e};else if("info"===a)a={i:c};else return;n+="&"+b.toQuery(a)}h=g.api_url+"/"+h+"?"+n;b.pii.transmits(h)||(b.createEl("img").src=h)},logException:function(a){if(g.debug){var c={link:b.cache(this,"link"),loc:document.location.href,UA:navigator.userAgent};
"string"===typeof a?c.message=a:c=b.extend(c,a);this.log("exception",a,b.toQuery(c))}},logTime:function(){var a;return function(c){0===arguments.length?a=(new Date).getTime():this.log("time",c,(new Date).getTime()-a)}}(),onApiClick:function(a,c,e,d,h){var n=d||b.getActualHref(a),k=b.bind(function(){this.redirect(n,b.context(a),c,e)},this);"object"===typeof h&&(h.tracking||h.image)?(d=b.createEl(h.tracking?"iframe":"img",{src:h.tracking||h.image},{height:0,width:0,visibility:"hidden"}),document.body.appendChild(d),
setTimeout(b.entryPoint(k),h.timeout||g.hop_timeout)):k()},onApiPing:function(a,c,e,f,h,n){g.rewrite_original=!1;h=b.reformatKeys(h||{});var k,l;f=function(a){var c={},e=function(a){b.isArray(a)?c[a[0]]=a[1]:c[a]=1};b.isArray(a)&&b.each(a,e);return c};l=b.extend(g.plugins,h.plugins);g=b.extend(g,h);delete g.plugins;g.click_timeout=c;g.library_id=a;g.time_ping&&this.logTime("png");"array"===b.type(g.testing_js)&&0<g.testing_js.length&&b.each(g.testing_js,function(a){b.jsonp(a)});b.extend(g.nofollow,
f(n));b.extend(g.norewrite,f(e));for(k in g)"on"===k.toLowerCase().substr(0,2)&&(2<k.length&&"function"===b.type(g[k]))&&(b.on(d,k.toLowerCase().substr(2),b.bind(g[k],window)),delete g[k]);this.initPlugins(l);this.initContext(window);this.fire("libready")},onClick:function(a,c){c=c||window.event;var e=c.ctrlKey||c.metaKey||c.altKey||c.shiftKey,d=c.which&&1===c.which||0===c.button,h=b.eventLink(c);if(h&&d&&!e&&!b.isDefaultPrevented(c)&&this.isRewritable(h)&&this.shouldHandleClick(a,h))return this.click(h),
b.preventDefault(c)},onContextmenu:function(a,c){var e=b.eventLink(c||window.event);e&&(this.isRewritable(e)&&this.shouldHandleClick(a,e))&&this.handleRightClick(e,"setup")},onCopy:function(a){var c,e,f,h=[];if(window.getSelection){e=window.getSelection();a=0;for(c=e.rangeCount;a<c;a++){try{f=e.getRangeAt(a).toString().replace(/((^)\s+|\s+$|\r)/g,"").replace(/\s*\n\s*/g,"\n")}catch(g){}0<f.length&&128>=f.length&&h.push(f)}}b.each(h,function(a){d.log("info",b.toQuery({type:"selection",txt:a,loc:location.href}))})},
opt:function(a,c){void 0!==c&&void 0!==this.publicOptions()[a]&&(g[a]=c);return g[a]},ping:function(){var a=!1;return function(){if(!a&&(g.key||g.dr_key)){var c={ref:document.referrer||null};a=!0;b.pii.transmits(this.api.now("ping",c,{"return":!0}))||(this.logTime(),this.detectFiltering(b.bind(function(a){a&&(g.batch_calls=!1,c.type=this.TYPE_ACCEPTABLE);this.api.now("ping",c,{fn:b.bind(this.onApiPing,this)})},this)))}}}(),platform:function(){return b.platforms.findById(g.platform)||b.platforms.NONE},
processLink:function(a){var c=b.cache(a,"processors")||{},e=this.isRewritable(a);b.each(this.registerProcessor(),function(b){!c[b.id]&&(e||b.opts.any)&&b.fn(a);c[b.id]=!0});b.cache(a,"processors",c);return a},processLinks:function(a){b.each(a,b.bind(this.processLink,this))},publicOptions:function(){var a={};return function(c){"object"===b.type(c)&&(a=c);return b.extend({},a)}}(),redirect:function(a,c,e,d){c=c||window.top;!b.traits.crossWindowCommunication&&!e?(d=c.open(a,d),d.focus()):b.traits.jsRedirectSetsReferrer?
setTimeout(b.entryPoint(function(){!e||e===c?c.location=a:b.contextIsAncestor(c,e)?e.location=a:e.location.replace(a)}),0):("_blank"===d&&(d=b.uniqid("win_")),d=b.createA(a,d),d.rel="norewrite",c.document.body.appendChild(d),d.click(),d.parentNode.removeChild(d))},runPlugin:function(a,c){var e=window.document,d=l[a];if(d&&d.initDocuments){if(c)d.initNodes(c);else if(d.init(),"function"===b.type(d.initDocuments)&&"document"===b.type(e)&&d.initDocuments([e]),"function"===b.type(d.initNodes)&&"element"===
b.type(e.body))b.on("DOMReady",function(){d.initNodes([e.body])});d._ran=!0}},registerProcessor:function(){var a=!1,c=[],e=function(e,d){if(void 0===e)return c;"function"===b.type(e)&&(d=b.extend({any:!1},d),c.push({fn:e,id:b.uniqid(),opts:d}),a&&this.initLinks())};e(function(){a=!0});return e}(),shouldHandleClick:function(a,c){var e=!0;a===this.EVENT_LEVEL_LINK&&(e=this.harmony(b.harmony.LINK_EVENTS)||this.isCommercial(c)&&this.harmony(b.harmony.COMMERCIAL_LINK_EVENTS));return e}};d.init();try{delete window.vglnk_self}catch(w){}})("undefined"===
typeof vglnk_self?"vglnk":vglnk_self);window.vglnk=window.vglnk||{};
window.vglnk.convert_plugin=function(m,d,b){var s={},g,l;m=d.extend({any:!0,convert_minimum_bid:!1},m);l={getDomains:function(){var g=[];d.each(s,function(b,d){2!==s[d]&&(g.push(d),s[d]=2)});0<g.length&&b.api("domains",{domains:g.join("|"),v:"2"},{fn:d.bind(l.onDomainApi,l)})},init:function(){b.opt("link_target",m.link_target);b.opt("rewrite_any",m.any);b.opt("rewrite_original",!0);(g=!m.any||b.harmony(d.harmony.COMMERCIAL_LINK_EVENTS)||m.convert_minimum_bid)&&b.registerProcessor(d.bind(function(b){this.initDomainLookup();
this.saveDomain(b)},this),{any:!0})},initDomainLookup:function(){var b=!1;return function(){b||(b=!0,d.on("DOMReady",d.bind(this.getDomains,this)))}}(),onDomainApi:function(g){var l;"object"===d.type(g)&&"array"===d.type(g.results)?(l=b.opt("commercial")||{},d.each(g.results,function(b){l[b]=!0}),b.opt("commercial",l)):"object"===d.type(g)&&"object"===d.type(g.results)&&(l=b.opt("commercial")||{},d.each(g.results,function(b,a){l[a]=b.unlink?!1:!0}),b.opt("commercial",l),b.registerProcessor(d.bind(function(b){this.minimumBidUnlink(b)},
this),{any:!0}))},saveDomain:function(b){b=d.canonicalizeHostname(b);s[b]=s[b]||1},minimumBidUnlink:function(g){var l=d.canonicalizeHostname(g);!1===(b.opt("commercial")||{})[l]&&d.unlink(g)}};return{init:d.bind(l.init,l),initNodes:function(){g&&l.getDomains()}}};window.vglnk=window.vglnk||{};
window.vglnk.crawler_plugin=function(m,d,b){var s=[],g=b.platform();m={crawl:function(b){if(g&&!("array"!==d.type(b)||0===b.length))b=d.all(b,function(b){return!d.contains(s,b)}),b=this.findPostsById(b),d.each(b,d.bind(function(b){b.content=this.redact(b.el.innerHTML.replace(/(^\s+|\s+$)/g,""));delete b.el},this)),b=d.all(b,function(b){return Boolean(b.content&&b.id)}),0<b.length&&this.processPosts(b)},findPostsById:function(b){return d.all(d.map(g.getPosts(),function(b){return{el:b,id:g.getPostId(b)}}),
function(g){return d.contains(b,g.id)})},processPosts:function(l){l=d.map(l,function(b){s.push(b.id);return{c:b.content,i:b.id}});b.api("content",{content:d.toJSON({ct:l,pt:g.id,u:location.href})},{jsonp:!1,ssl:b.opt("dev")?!1:!0})},redact:function(b){return d.pii.redact(b)}};return{"public":{crawl:d.bind(m.crawl,m)}}};window.vglnk=window.vglnk||{};window.vglnk.modified_clicks_plugin=function(m,d,b){return{init:function(){b.opt("rewrite_modified",!0)}}};window.vglnk=window.vglnk||{};
window.vglnk.dr_search_box_plugin=function(m,d,b){m=d.extend({key:null},m);var s={init:function(b){d.each(this.getDRSearchForms(b),function(b){if(!d.cache(b,"evented")){var g=s.getInput(b),m=function(){g.value||d.css(g,{"background-image":"url(http://cdn.viglink.com/images/ebay_watermark.gif)"})};d.cache(b,"evented",!0);b.onsubmit=null;g.onfocus=null;g.onblur=null;d.on(g,"focus",function(){d.css(g,{"background-image":"none"})});d.on(g,"blur",m);m();d.on(b,"submit",function(d){s.onSubmit(d,b)})}})},
getDRSearchForms:function(b){var l=[];d.each(b,function(b){"element"===d.type(b)&&d.each(b.getElementsByTagName("form"),function(b){s.getInput(b)&&b.id.match(/^DR-ebay-search(CSS|2)?$/i)&&l.push(b)})});return l},getInput:function(b){return b.p||b.q2},onSubmit:function(g,l){g=g||window.event;var n="http://shop.ebay.com/i.html?"+d.toQuery({_nkw:s.getInput(l).value}),n=d.createA(n,"_blank");d.cache(n,"params",{key:m.key});b.click(n);return d.preventDefault(g)}};if(m.key)return{init:d.bind(s.init,s),
initNodes:function(b){s.init(b)}}};window.vglnk=window.vglnk||{};window.vglnk.harmony_plugin=function(m,d,b){m=d.extend({level:d.harmony.DEFAULT},m);return{init:function(){var d=parseFloat(m.level,10);isFinite(d)&&b.opt("harmony_level",d)}}};window.vglnk=window.vglnk||{};
window.vglnk.optimize_plugin=function(m,d,b,s){var g,l={uuid:"uuid",index:"idx",optimized_url:"url",aliases:"aka"};g={cache:function(){var b={},d={};return{links:{get:function(d){return b[d]},set:function(d,a){var c={};c[l.optimized_url]=a[l.optimized_url];c[l.uuid]=a[l.uuid];c[l.aliases]=a[l.aliases];b[d]=c}},stats:{increment:function(b,a){d[b]||(d[b]={});if(a)if("rep"===a)d[b].rep=(d[b].rep||0)+1;else{var c;c=d[b].ex=d[b].ex||{};c[a]=(c[a]||0)+1}else d[b].n=(d[b][l.insertion_count]||0)+1},getAndReset:function(){var b=
d;d={};return b}}}}(),filterLinkNodes:function(){var b={sameDomainOrInternal:function(){var b=window.location.hostname;return function(a){return b===a.hostname}}()},m=function(g){return d.all(g,function(a){return d.every(b,function(c){return!c(a)})})};return function(b){var a={needs_optimization:[],needs_call:[]};d.each(m(b),function(c){var b=g.cache.links.get(c.href);b&&b[l.uuid]&&d.cache(c,"uuid",b[l.uuid]);b&&b[l.optimized_url]?a.needs_optimization.push(c):b&&"false"===b[l.optimized_url]||a.needs_call.push(c)});
return a}}(),generateAliases:function(b){var m=g.cache.links.get(b.href),w=[],w=w.concat(m[l.aliases]||[]);w.push(d.canonicalizeHostname(b.href));w.push(d.canonicalizeHostname(m[l.optimized_url]));return d.unique(w)},getLinks:function(){var n=function(b){var g=[];d.each(b,function(a){g.push(a.href)});return g};return function(l){var m=d.unique(n(l));b.api_now("optimize",{links:m,u:location.href,ver:2},{fn:d.bind(g.onOptimizeApi,g)},m,l)}}(),log:d.batchable(function(){var b={stats:d.toJSON(g.cache.stats.getAndReset())};
4<b.stats.length&&s("loJsLog",b)},function(){return{timeout:1E3}}),onOptimizeApi:function(b,m,s){"object"===d.type(b)&&(d.each(["opt","non","unk"],function(a){b[a]&&b[a].length&&d.each(b[a],function(c){var b=m[c[l.index]];"non"===a&&(c[l.optimized_url]=!1);g.cache.links.set(b,c)})}),s=g.filterLinkNodes(s),g.optimizeLinks(s.needs_optimization))},optimizeLinks:function(b){d.each(b,function(b){d.cache(b,"rewrit",!1)});b=g.runExclusionFilters(b);d.each(b,this.optimizeLink);d.traits.json&&g.log()},optimizeLink:function(){var b=
function(a){return a.replace(/^https?:\/\//,"")},p=function(a,c){for(var b;b=a.firstChild;)a.removeChild(b);a.appendChild(document.createTextNode(c))},s=function(a){var c=a.href,e=a.textContent||a.innerText,f=Boolean(e),h=g.generateAliases(a),l=function(){var a=b(c).toLowerCase(),f=e.toLowerCase().replace(a,"");return d.some(h,function(a){return-1!==f.indexOf(a.toLowerCase())})},k=function(){var a=e.split(/(?:\.\.\.|\u2026)/);return 2>a.length?!1:RegExp("^"+d.map(a,d.escapeRegExp).join(".+")+"$").test(c)},
m=function(){var c=d.canonicalizeHostname(a);return d.canonicalizeHostname(d.createEl("a",{href:e}))===c},q=function(){var c;return m()?(c=d.fromQuery(a.search),d.find(c,function(a){return a===e})):!1};return{full_replace:Boolean(f&&(c===e||b(c)===e||k()||q())),exclude:Boolean(f&&l()),partial_replace:Boolean(f&&(-1!==e.indexOf(c)||-1!==e.indexOf(b(c))))}};return function(a){var c,e=g.cache.links.get(a.href),f=e[l.optimized_url];c=s(a);if(f&&!m.observer){if(c.full_replace)p(a,f),g.cache.stats.increment(e[l.uuid],
"rep");else{if(c.exclude){g.cache.stats.increment(e[l.uuid],"a");return}c.partial_replace&&(c="undefined"!==d.type(a.textContent)?a.textContent:a.innerText,c=-1!==c.indexOf(a.href)?c.replace(a.href,f):c.replace(b(a.href),f),p(a,c),g.cache.stats.increment(e[l.uuid],"rep"))}f=-1===f.indexOf("http://")?"http://"+f:f;a.href=f}g.cache.stats.increment(e[l.uuid]);d.cache(a,"rewrit",!0)}}(),runExclusionFilters:function(){var b=d.generateNodeFilter({classes:["nooptimize","norewrite"],rels:["nooptimize","norewrite",
"noskim"],custom:function(a,c){if(c)return Boolean(d.cache(a,"type"))}}),m=function(a){var c=g.generateAliases(a),b=d.context(a).document.title;return d.every(c,function(a){return-1===b.indexOf(a)})},s=function(){var a=function(a,c){var b=d.reduce([],["prev_tokens","next_tokens"],function(c,b){a[b]&&a[b].length&&(c=c.concat(a[b]));return c}).join(" ").toLowerCase();return d.some(c,function(a){return-1!==b.indexOf(a.toLowerCase())})},c=function(){var a=function(a){a="undefined"!==d.type(a.textContent)?
a.textContent:a.innerText;return d.all(a.split(/\s+/g),function(a){return""!==a})};return function(c){for(var b={prev_tokens:[],next_tokens:[]};c&&c!==document.body.parentNode;){for(var g=b,k=c.previousSibling,l=c.nextSibling;k||l;)k&&(d.nodesOfType([k],1,3).length&&"SCRIPT"!==k.tagName)&&(g.prev_tokens=g.prev_tokens.concat(a(k).reverse())),k=!k?!1:k.previousSibling,l&&(d.nodesOfType([l],1,3).length&&"SCRIPT"!==l.tagName)&&(g.next_tokens=g.next_tokens.concat(a(l))),l=!l?!1:l.nextSibling;if(20<b.prev_tokens.length+
b.next_tokens.length+0)break;c=c.parentNode}return b}}();return function(b){var d=g.generateAliases(b);b=c(b);80<b.prev_tokens.length+b.next_tokens.length+0&&(b.prev_tokens=b.prev_tokens.slice(0,40),b.next_tokens=b.next_tokens.slice(0,40));b.prev_tokens=b.prev_tokens.reverse();return!a(b,d)}}();return function(a){return d.all(a,function(a){var d=g.cache.links.get(a.href)[l.uuid];if(b(a))if(s(a)){if(!m(a))return g.cache.stats.increment(d,"t"),!1}else return g.cache.stats.increment(d,"p"),!1;else return g.cache.stats.increment(d,
"n"),!1;return!0})}}()};return{initNodes:function(b){var l;b=d.nodesOfType(b,1);b=d.withScope(b,"a[href]",{ancestors:!1,consolidate:!0});b=g.filterLinkNodes(b);(l=b.needs_optimization)&&l.length&&g.optimizeLinks(l);(b=b.needs_call)&&b.length&&g.getLinks(b)}}};window.vglnk=window.vglnk||{};
window.vglnk.insert_plugin=function(m,d,b,s){var g,l,n,p,w=null,a=null;m=d.extend({cat:null,key:null,link_phrases:!0,link_target:null,link_urls:!0,manual_mode:1===m.mode,per_page:null,per_phrase:5,proximity:null,same_proximity:100,scope:null,ui:!0},m);if(m.key)return g=b.platform(),l={cache:function(){var a={},b={},f=function(f,h){var g={};d.isArray(h)&&0<h.length&&d.find(h,function(a){var c=b;if(c[a]){if(f)return g[f]=c[a][f],!0;d.each(c[a],function(a,b){g[b]||(g[b]=a)})}});g=d.extend(d.clone(a),
g);return f?g[f]:g},h=function(f,h,g){(g=d.isArray(g)&&0<g.length?g:null)&&d.each(g,function(a){var c=b;c[a]=c[a]||{};"L"!==h.type&&(c[a][f]=h)});if(!g||"L"===h.type)a[f]||(a[f]=h);return!0},g=function(a,b,c){var e=d.all(d.toArray(arguments),function(a){return Boolean(a)});"array"===d.type(e[e.length-1])&&(c=e.pop());a=e[0];b=e[1];if(1>=e.length)return f(a,c);if(2===e.length)return h(a,b,c)};m.manual_mode&&d.extend(g,{reset:function(){a={};b={}}});return g}(),focusLink:function(a){a.id||(a.id=d.uniqid("vl-link-"));
location.href.hash="#"+a.id;window.scrollBy(0,-150)},getPartnerParams:function(){var a,d,f=b.opt("partner"),h={};for(a in f)break;if(a)for(d in f[a])h[a+"_"+d]=f[a][d];return h},getPhrases:function(a,e){b.api("insert",d.extend(l.getPartnerParams(),{cat:m.cat,i:e?e.join("|"):null,mode:m.mode,pt:g.id,ps:m.product_source,u:location.href}),{fn:d.bind(l.onInsertApi,l)},a,e)},hasCalled:function(){var a={},b=function(b){return d.isArray(b)&&b.length?Boolean(d.all(b,function(b){return a[b]}).length===b.length):
Boolean(a[d.platforms.DEFAULT_POST_ID])},f=function(b){d.isArray(b)&&b.length?d.each(b,function(b){a[b]=!0}):a[d.platforms.DEFAULT_POST_ID]=!0};return function(a,c){return c?f(a):b(a)}}(),init:function(){m.scope=m.scope||g.scope;m.link_urls&&(p=RegExp("(?:(?:\\b(https?://)|(?:^|\\s)\\W*(www\\d{0,3}\\.|(?:[a-z0-9-]+\\.)+[a-z]{2,4}/))((?:[^\\s()<>]+|\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\))+(?:\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\)|[^\\s`!()\\[\\]{};:'\".,<>?\u00ab\u00bb\u201c\u201d\u2018\u2019]))|(?:^|\\s)\\W*((?:[a-z0-9-]+\\.)+com(?:/|\\b)))",
"i"))},initLink:function(a,e,f){var g=m.link_target;if(g="U"===e.type?b.opt("link_target"):g||f)a.target=g;a.href||(a.href=e.url);a.rel="nofollow";d.cache(a,"params",{exp:w,key:m.key,mid:e.mid,type:e.type||null});d.cache(a,"href",a.href);b.link(a)},insertLinks:function(){var a,b=d.generateNodeFilter({classes:["nolinks","atma-nolink","atma-nolinks"],tags:"applet embed object head img input link map meta param select button iframe option script style svg textarea title".split(" "),custom:function(a){return d.matches(a,
"a")&&Boolean(a.href)}}),f=function(a,c,d,k){if(b(c,{ancestors:!Boolean(k),self:!0}))if(3===c.nodeType)g(a,c,d);else if(1===c.nodeType)for(c=c.firstChild;c;)k=c.nextSibling,f(a,c,d,!0),c=k},g=function(a,b,c){var d=!1,e=b.parentNode,f=function(a,b){e.insertBefore(a,b);e.removeChild(b)};e&&(b.data&&(d=a.test(b.data.replace(/\s+/," "))),d&&n(a,b,c,f))},n=function(b,e,f,g){for(var h,n,p,r,s=function(b){var e;b=!b||!m.per_phrase||!a[b.phrase]||a[b.phrase].count<m.per_phrase;e=!m.per_page||d.reduce(0,a,
function(a,b){return a+b.count})<m.per_page;return b&&e},w=function(a,b,c){var e,f,g;if(!c.phrase)return!0;f=d.createEl("span");b.parentNode.insertBefore(f,b);f.appendChild(b);g=d.geometry(f);(m.proximity||m.same_proximity)&&d.find(l.cache(a),function(a){var b,f;if(a.links){if((b=l.normalizePhrase(a.phrase)===l.normalizePhrase(c.phrase))&&!m.same_proximity||!b&&!m.proximity)return!1;f=b?Math.max(m.same_proximity,m.proximity):m.proximity;a.links=d.all(a.links,function(a){var b=d.isInDom(a.el);!e&&
b&&(e=d.find(a.segments,function(a){a=a.geometry;a=d.extend({},a);a.x1-=f;a.y1-=f;a.x2+=f;a.y2+=f;if(a.x1<g.x2&&a.x2>g.x1&&a.y1<g.y2&&a.y2>g.y1)return!0}));return b});return e}});return function(a){f.parentNode.insertBefore(b,f);f.parentNode.removeChild(f);return a}(!e)},T=function(a,b){var c,e,f,g,h={el:a,segments:[]},k=a.getElementsByTagName("span"),l={els:[]};c=0;for(e=k.length;c<e;c++)f=k[c],void 0===g||f.offsetTop===g.offsetTop?l.els.push(f):(h.segments.push(l),l={els:[f]}),g=f;l.geometry=d.geometry.apply(d,
l.els);h.segments.push(l);b.links=b.links||[];b.links.push(h);return b};e&&e.data&&""!==e.data&&(Boolean(p=e.data.match(/^\s+/))||Boolean(p=e.data.match(b)));)n=p[0],r=p.slice(1).join(""),h=(h=l.normalizePhrase(r))?l.cache(h,f):null,n=e.data.indexOf(n)+n.length-r.length,0<n&&(e=e.splitText(n)),n=e.length<=r.length?null:e.splitText(r.length),r&&!h&&(h={url:r.match(/^https?:\/\//i)?r:"http://"+r,type:"U"}),h&&(h.url.match(/https?:\/\//i)&&r&&s(h)&&w(f,e,h))&&(r=k(r,h),d.cache(r,"unlinked")||(g(r,e),
T(r,h),e=h.phrase||h.url,a[e]=a[e]||{count:0,phrase:h.phrase,type:h.type},a[e].count++)),e=n},k=function(a,b){var c;c=d.createEl("a");c.innerHTML=a.replace(/([a-z0-9]+ *|[^a-z0-9]+)/ig,"<span>$1</span>");c.className="vglnk";d.cache(c,"type","inserted");d.cache(c,"phrase",a);m.ui&&"U"!==b.type&&(c.title="Link added by VigLink");l.initLink(c,b);return c};return function(g,h){var k=l.regexp(h);a={};k&&(d.each(d.all(g,b),function(a){f(k,a,h)}),m.link_phrases&&l.log(a))}}(),insertManually:function(){var a=
!1,b=d.clone(m),f=function(a){return d.map(a,function(a,b){return{phrase:b,type:"M",url:a}})};return function(g,p,k){var s,q=!1;n.init();m.manual_mode&&!a&&(a=!0,s=p=p||{},m.same_proximity=s.same_proximity||m.same_proximity,m.proximity=s.proximity||m.proximity,m.per_page=s.per_page||m.per_page,m.per_phrase=s.per_phrase||m.per_phrase,s=p.target_node||document.body,g=f(g),l.loadPhrases(g,[s]),m=b,l.cache.reset(),q=!0,a=!1);"function"===d.type(k)&&k(q,s)}}(),loadPhrases:function(a,b,f){d.each(a,function(a){a.phrase&&
a.url&&(a.phrase=l.normalizePhrase(a.phrase),l.cache(a.phrase,{count:0,phrase:a.phrase,mid:a.mid,url:a.url,type:a.type||""},f))});l.hasCalled(f,!0);this.insertLinks(b,f)},log:function(b){var e=0,f=0,g=[];d.each(b,function(a,b){var c=parseInt(a.count,10);0<c&&("U"===a.type?f+=c:"M"!==a.type&&g.push({phrase:b,type:a.type,count:c}),e+=c)});0<e&&s("insert",[{ct:e,cl:f,exp:w,imp_id:a,phrases:d.toJSON(g)}])},normalizePhrase:function(a){return a.toLowerCase().replace(/(^\s+|\s+$)/g,"").split(/\s+/).join(" ")},
onInsertApi:function(b,e,f){"object"===d.type(b)&&(w=b.exp,a=b.imp_id,b.results&&this.loadPhrases(b.results,e,f))},regexp:function(a){var b;a=l.cache(a);a=d.map(a,function(a,b){return d.escapeRegExp(b).split(" ").join("\\s+")});0<a.length&&(b="(?:^|[\\s\"'\\(])("+a.join("|")+")(?=\\s|\\W*$|\\W{2})",b=RegExp(p?"(?:"+b+"|"+p.source+")":b,"i"));return b||p}},n={init:d.destructing(d.bind(l.init,l)),initNodes:function(a){var b;m.scope&&(a=d.unique(d.reduce([],d.withScope(a,m.scope),function(a,b){return a.concat(b[1])})));
a.length&&(b=g.getPostIds(a),m.link_phrases&&!l.hasCalled(b)?l.getPhrases(a,b):l.insertLinks(a,b))}},m.manual_mode&&d.extend(n,{"public":{run:l.insertManually}}),n};window.vglnk=window.vglnk||{};window.vglnk.partners_plugin=function(m,d,b){var s={run:function(){var g,l=m.pai_type;d.isArray(l)&&l.length&&d.each(l,function(l){g=d.updateUrl(b.opt("api_url"),{pathname:"/api/sync.gif",search:"?"+d.toQuery({partner_id:l})});d.createEl("img").src=g})}};return{init:function(){s.run()}}};
